# Generated by Django 3.0.3 on 2020-02-20 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Orderd', models.DateTimeField()),
                ('Odered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='Shop.Ordered_Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.SlugField(default='shop19736')),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('passport', models.ImageField(default='noimage.png', upload_to='')),
                ('pvc', models.ImageField(default='noimage.png', upload_to='')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.SlugField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('type', models.CharField(choices=[('FS', 'Fashion'), ('PT', 'Phone & Tablets'), ('EL', 'Electronics'), ('HO', 'Home & Office'), ('CP', 'Computing')], max_length=2)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('VG', 'Very Large')], max_length=2)),
                ('shop', models.ManyToManyField(to='Shop.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='item',
            field=models.ManyToManyField(to='Shop.Product'),
        ),
    ]
