# Generated by Django 3.0.3 on 2020-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(default=600756),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop22339'),
        ),
    ]
