# Generated by Django 3.0.3 on 2020-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200220_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sample',
            field=models.ImageField(default=22, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(default=721827),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop26181'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='Date_Orderd',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
