# Generated by Django 3.0.3 on 2020-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200226_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=333991),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop34849'),
        ),
    ]
