# Generated by Django 3.0.3 on 2020-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20200226_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=934954),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop40528'),
        ),
    ]
