# Generated by Django 3.0.3 on 2020-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20200226_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sample',
            field=models.ImageField(blank=True, default='noimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=766725),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop45370'),
        ),
    ]
