# Generated by Django 3.0.3 on 2020-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_auto_20200226_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='manager',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=490068),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop14734'),
        ),
    ]
