# Generated by Django 3.0.3 on 2020-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20200227_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=318902),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.SlugField(default='shop65777'),
        ),
    ]
