# Generated by Django 3.0.3 on 2020-02-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('P_type', models.CharField(choices=[('FS', 'Fashion'), ('PT', 'Phone & Tablets'), ('EL', 'Electronics'), ('HO', 'Home & Office'), ('CP', 'Computing')], max_length=2)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('VG', 'Very Large')], max_length=2)),
                ('sample', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('items', models.ManyToManyField(to='Shopping.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping.OrderedItem')),
            ],
        ),
    ]
