# Generated by Django 3.0.3 on 2020-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0006_auto_20200228_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=296746),
        ),
    ]
