# Generated by Django 3.0.3 on 2020-02-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0009_auto_20200228_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='item',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item',
            field=models.ManyToManyField(to='Shopping.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=928404),
        ),
    ]
