# Generated by Django 3.0.3 on 2020-02-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0017_auto_20200229_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='seize',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=564215),
        ),
    ]
