# Generated by Django 3.0.3 on 2020-02-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0018_auto_20200229_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='seize',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=526845),
        ),
    ]
