# Generated by Django 3.0.3 on 2020-02-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0019_auto_20200229_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Shopping.OrderedItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=170109),
        ),
    ]
