# Generated by Django 3.0.3 on 2020-02-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0022_auto_20200229_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=334540),
        ),
    ]
