# Generated by Django 3.0.3 on 2020-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0023_auto_20200229_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=928182),
        ),
    ]
