# Generated by Django 3.0.3 on 2020-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0029_auto_20200302_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=516190),
        ),
    ]
