# Generated by Django 3.0.3 on 2020-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0032_auto_20200302_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=753703),
        ),
    ]
