# Generated by Django 3.0.3 on 2020-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0041_auto_20200303_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=371440),
        ),
    ]
