# Generated by Django 3.0.3 on 2020-03-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0042_auto_20200303_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=445536),
        ),
    ]
