# Generated by Django 3.0.3 on 2020-03-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0044_auto_20200308_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=784333),
        ),
    ]
