# Generated by Django 3.0.3 on 2020-03-09 11:20

import Shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0045_auto_20200308_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-Date']},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='payment_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sample',
            field=models.ImageField(upload_to=Shopping.models.save_sample_with_uiid),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=389082),
        ),
    ]
