# Generated by Django 3.0.3 on 2020-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0046_auto_20200309_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_type',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=878454),
        ),
    ]
