# Generated by Django 3.0.3 on 2020-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0047_auto_20200309_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=292637),
        ),
    ]
