# Generated by Django 3.0.3 on 2020-07-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0048_auto_20200722_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=125817),
        ),
    ]
