# Generated by Django 3.0.3 on 2020-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0049_auto_20200722_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=239123),
        ),
    ]
