# Generated by Django 3.0.3 on 2020-07-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0050_auto_20200722_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=235969),
        ),
    ]
