# Generated by Django 3.0.3 on 2020-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0051_auto_20200722_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=630062),
        ),
    ]
