# Generated by Django 3.0.3 on 2020-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0054_auto_20200722_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=732643),
        ),
    ]
