# Generated by Django 3.0.3 on 2020-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0055_auto_20200722_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=504946),
        ),
    ]
