# Generated by Django 3.0.3 on 2020-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0056_auto_20200722_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=274801),
        ),
    ]
