# Generated by Django 3.0.3 on 2020-07-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0057_auto_20200722_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=234789),
        ),
    ]
